/**
 * TermsModal — inline Terms of Service / Privacy Policy viewer.
 *
 * Usage:
 *   const [termsType, setTermsType] = useState<'terms' | 'privacy' | null>(null)
 *   <TermsModal type={termsType} onClose={() => setTermsType(null)} />
 *
 * Replace placeholder content with real copy when legal docs are ready.
 */

import { Info, X } from 'lucide-react'
import { useCallback, useEffect } from 'react'

import styles from './terms-modal.module.css'

export type TermsType = 'terms' | 'privacy'

export interface TermsModalProps {
  type: TermsType | null
  onClose: () => void
}

const CONTENT: Record<
  TermsType,
  { title: string; sections: Array<{ heading: string; body: string }> }
> = {
  terms: {
    title: 'Terms of Service',
    sections: [
      {
        heading: 'Acceptance of Terms',
        body: 'By accessing or using Neo-Kanban ("the Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use the Service.',
      },
      {
        heading: 'Use of Service',
        body: 'Neo-Kanban is an AI-agentic project management platform. You may use the Service for lawful software development purposes only. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.',
      },
      {
        heading: 'AI-Generated Content',
        body: 'The Service uses large language models to generate code, specifications, and plans. AI-generated outputs may contain errors or inaccuracies. You are solely responsible for reviewing, validating, and accepting any AI-generated code before integrating it into your projects.',
      },
      {
        heading: 'API Keys & Security',
        body: 'You are responsible for the secure management of any third-party API keys (Groq, OpenAI, Anthropic, Google) configured in the Service. Never share your API keys. Neo-Kanban stores keys server-side and never exposes them in the frontend.',
      },
      {
        heading: 'Intellectual Property',
        body: 'Code and artifacts generated by the AI coding backends remain your intellectual property. Neo-Kanban claims no ownership over content you create or generate using the Service.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'The Service is provided "as is" without warranties of any kind. Neo-Kanban shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.',
      },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    sections: [
      {
        heading: 'Information We Collect',
        body: 'We collect your email address and display name when you register. We also collect usage data including project names, task descriptions, and agent interaction logs to operate the Service.',
      },
      {
        heading: 'How We Use Information',
        body: 'Your data is used solely to provide and improve the Service. We do not sell or share your personal information with third parties except as required to operate the Service (e.g., LLM API providers).',
      },
      {
        heading: 'LLM API Providers',
        body: 'When you use AI-powered features, your prompts and task context are sent to the configured LLM provider (Groq, OpenAI, Anthropic, or Google). These providers have their own privacy policies governing how they handle data.',
      },
      {
        heading: 'Data Storage',
        body: 'Your data is stored in a PostgreSQL database hosted on your configured infrastructure. You control where and how your data is stored by choosing your deployment environment.',
      },
      {
        heading: 'Authentication & Tokens',
        body: 'Authentication uses JWT tokens stored in your browser\'s localStorage. Tokens expire after 7 days. You can revoke access at any time by logging out, which removes the token from storage.',
      },
      {
        heading: 'Your Rights',
        body: 'You may request deletion of your account and associated data at any time by contacting us or using the account settings page.',
      },
    ],
  },
}

export function TermsModal({ type, onClose }: TermsModalProps) {
  const open = type !== null

  // ESC key closes
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() },
    [onClose],
  )

  useEffect(() => {
    if (!open) return
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [open, handleKeyDown])

  if (!open || !type) return null

  const content = CONTENT[type]

  return (
    <div
      className={styles.backdrop}
      role="presentation"
      onClick={onClose}
    >
      <div
        className={styles.panel}
        role="dialog"
        aria-modal="true"
        aria-labelledby="terms-modal-title"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className={styles.header}>
          <div>
            <h2 id="terms-modal-title" className={styles.title}>
              {content.title}
            </h2>
            <p className={styles.lastUpdated}>Last updated: May 2026 · Draft</p>
          </div>
          <button
            type="button"
            className={styles.closeBtn}
            onClick={onClose}
            aria-label={`Close ${content.title}`}
          >
            <X size={18} strokeWidth={2} aria-hidden="true" />
          </button>
        </div>

        {/* Scrollable body */}
        <div className={styles.body}>
          <div className={styles.placeholder}>
            <Info size={14} aria-hidden="true" />
            <span>Placeholder — replace with final legal copy before production.</span>
          </div>

          {content.sections.map(({ heading, body }) => (
            <div key={heading} className={styles.section}>
              <h3 className={styles.sectionTitle}>{heading}</h3>
              <p className={styles.sectionText}>{body}</p>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className={styles.footer}>
          <button type="button" className={styles.closeTextBtn} onClick={onClose}>
            I understand
          </button>
        </div>
      </div>
    </div>
  )
}
